/*
   요구사항
   음료수 판매 업체입니다. 음료수마다 당첨번호가 있습니다. 
   음료수의 당첨번호는 1개이고 당첨자의 정보를 알아야 상품을 배송할 수 있습니다.
   당첨 번호마다 당첨 상품이 있고, 당첨 상품이 배송 중인지 배송 완료인지 구분해야 합니다.
*/

--CREATE SEQUENCE SEQ_DRINK;
--CREATE TABLE TBL_DRINK(
--	ID NUMBER CONSTRAINT PK_DRINK PRIMARY KEY,
--	DRINK_NAME VARCHAR2(255) NOT NULL,
--	DRINK_WINNING NUMBER UNIQUE NOT NULL,
--	DRINK_PRODUCT NUMBER CONSTRAINT FK_PRODUCT REFERENCES TBL_PRODUCT(ID),
--	DRINK_WINNER NUMBER CONSTRAINT FK_WINNER REFERENCES TBL_WINNER(ID)
--);
--
--CREATE SEQUENCE SEQ_PRODUCT;
--CREATE TABLE TBL_PRODUCT(
--	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
--	PRODUCT_NAME VARCHAR2(255),
--	PRODUCT_DELIVERY VARCHAR2(255)
--);
--
--CREATE SEQUENCE SEQ_WINNER;
--CREATE TABLE TBL_WINNER(
--	ID NUMBER CONSTRAINT PK_WINNER PRIMARY KEY,
--	WINNER_NAME VARCHAR2(255),
--	WINNER_ADDRESS VARCHAR2(255)
--);

/*

CREATE SEQUENCE SEQ_DRINK;
CREATE TABLE TBL_DRINK(
   ID NUMBER CONSTRAINT PK_DRINK PRIMARY KEY,
   DRINK_NAME VARCHAR2(255),
   DRINK_COUNT NUMBER,
   DRINK_WIN NUMBER
   DRINTK_WIN_STATUS VARCHAR(10) DEFAULT '꽝'
);

CREATE SEQUENCE SEQ_WINNER;
CREATE TABLE TBL_WINNER(
   ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
   WINNER_NAME VARCHAR(255),
   WINNER_ADDRESS VARCHAR(255)
);

CREATE SEQUENCE SEQ_DELIVERY;
CREATE TABLE TBL_DELIVERY(
   ID DELIVERY CONSTRAINT PK_DELIVERY PRIMARY KEY,
   DELIVERY_STATUS CHAR(10) DEFAULT '배송 중',
   WINNER_ID NUMBER,
   DRINK_ID NUMBER,
   CONSTRAINT FK_DELIVERY_WINNER FOREIGN KEY(WINNER_ID)
   REFERENCES TBL_WINNER(ID),
   CONSTRAINT FK_DELIVERY_DRINK FOREIGN KEY(DRINK_ID)
   REFERENCES TBL_DRINK(ID)
);

*/

-- 사용자 1
-- 주문테이블 N - FK 사용자, FK 음료수
-- 음료수 1
-- 운 - FK 음료수
-- 상품 1
-- 추첨 - FK 운, FK 상품
-- 배송 - FK 상품, FK 사용자

-- 사용자 1
CREATE SEQUENCE SEQ_USER;
CREATE TABLE TBL_USER(
   ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
   USER_NAME VARCHAR2(255) NOT NULL,
   USER_ADDRESS VARCHAR2(255) NOT NULL,
   USER_PHONE VARCHAR(255) NOT NULL
);

-- 음료수 1
CREATE SEQUENCE SEQ_SOFT_DRINK;
CREATE TABLE TBL_SOFT_DRINK(
   ID NUMBER CONSTRAINT PK_SOFT_DRINK PRIMARY KEY,
   SOFT_DRINK_NAME VARCHAR2(255) NOT NULL UNIQUE,
   SOFT_DRINK_PRICE NUMBER DEFAULT 0,
   SOFT_DRINK_STOCK NUMBER DEFAULT 999,
   SOFT_DRINK_MAKE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 상품 1
CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
   ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
   PRODUCT_NAME VARCHAR(255) NOT NULL UNIQUE,
   PRODUCT_STOCK NUMBER DEFAULT 999
);

-- 주문 - FK사용자, FK음료수
CREATE SEQUENCE SEQ_ORDER;
CREATE TABLE TBL_ORDER(
   ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   USER_ID NUMBER,
   SOFT_DRINK_ID NUMBER,
   CONSTRAINT FK_ORDER_USER FOREIGN KEY(USER_ID)
   REFERENCES TBL_USER(ID),
   CONSTRAINT FK_ORDER_SOFT_DRINK FOREIGN KEY(SOFT_DRINK_ID)
   REFERENCES TBL_SOFT_DRINK(ID)
);

-- 운 FK - 음료수
CREATE SEQUENCE SEQ_LOTTERY;
CREATE TABLE TBL_LOTTERY(
   ID NUMBER CONSTRAINT PK_LOTTERY PRIMARY KEY,
   SOFT_DRINK_ID NUMBER,
   CONSTRAINT FK_LOTTERY_SOFT_DRINK FOREIGN KEY(SOFT_DRINK_ID)
   REFERENCES TBL_SOFT_DRINK(ID)
);

-- 추첨 FK운, FK상품
CREATE SEQUENCE SEQ_CIRULATION;
CREATE TABLE TBL_CIRULATION(
   ID NUMBER CONSTRAINT PK_CIRULATION PRIMARY KEY,
   LOTTERY_ID NUMBER,
   PRODUCT_ID NUMBER,
   CONSTRAINT FK_CIRULATION_LOTTERY FOREIGN KEY(LOTTERY_ID)
   REFERENCES TBL_LOTTERY(ID),
   CONSTRAINT FK_CIRULATION_PRODUCT FOREIGN KEY(PRODUCT_ID)
   REFERENCES TBL_PRODUCT(ID)
);

-- 배송 FK상품, FK사용자
CREATE SEQUENCE SEQ_DELIVERY;
CREATE TABLE TBL_DELIVERY(
   ID NUMBER CONSTRAINT PK_DELIVERY PRIMARY KEY,
   PRODUCT_ID NUMBER,
   USER_ID NUMBER,
   CONSTRAINT FK_DELIVERY_PRODUCT FOREIGN KEY(PRODUCT_ID)
   REFERENCES TBL_PRODUCT(ID),
   CONSTRAINT FK_DELIVERY_USER FOREIGN KEY(USER_ID)
   REFERENCES TBL_USER(ID)
);

-----

/*
요구사항
   이커머스 창업 준비중입니다. 
   기업과 사용자 간 거래를 위해 기업의 정보와 사용자 정보가 필요합니다.
   기업의 정보는 기업 이름, 주소, 대표번호가 있고
   사용자 정보는 이름, 주소, 전화번호가 있습니다. 
   결제 시 사용자 정보와 기업의 정보, 결제한 카드의 정보 모두 필요하며,
   상품의 정보도 필요합니다. 상품의 정보는 이름, 가격, 재고입니다.
   사용자는 등록한 카드의 정보를 저장할 수 있으며, 
   카드의 정보는 카드번호, 카드사, 회원 정보가 필요합니다.
*/

-----
--			FIELD										FK
-- 기업 : 이름, 주소, 대표번호					+ 결제 정보(결제 테이블의 특정 값) + 상품
-- 사용자 : 이름, 주소, 전화번호 , 카드의 정보		+ 사용자의 카드 회사 (카드 회사의 본인의 카드 리스트)
-- 카드 리스트 : 카드번호, 카드사				+ 회원 정보
-- 카드사 : 								+ 회원 정보(회원의 당사 카드 리스트)
-- 상품 : 이름, 가격, 재고					+ 기업 정보
-- 결제 테이블 : 기업, 사용자, 결제한 카드의 정보	+ 결제한 상품

-----

-- 기업 : 이름, 주소, 대표번호					+ 결제 정보(결제 테이블의 특정 값) + 상품
--CREATE SEQUENCE SEQ_ENTERPRISE;
--CREATE TABLE TBL_ENTERPRISE(
--	ID NUMBER CONSTRAINT PK_ENTERPRISE PRIMARY KEY,
--	ENTERPRISE_NAME VARCHAR2(255) NOT NULL,
--	ENTERPRISE_ADDRESS VARCHAR2(255) NOT NULL UNIQUE,
--	ENTERPRISE_CALL_NUMBER VARCHAR2(255) NOT NULL,
--	FK_PAYMENT_ID NUMBER
--	FK_PRODUCT_ID NUMBER
--);
--
-- 사용자 : 이름, 주소, 전화번호 , 카드의 정보		+ 사용자의 카드 회사 (카드 회사의 본인의 카드 리스트)
--CREATE SEQUENCE SEQ_CUSTOMER;
--CREATE TABLE TBL_CUSTOMER(
--	ID NUMBER CONSTRAINT PK_CUSTOMER PRIMARY KEY,
--	CUSTOMER_NAME VARCHAR2(255) NOT NULL,
--	CUSTOMER_ADDRESS VARCHAR2(255) NOT NULL UNIQUE,
--	CUSTOMER_CALL_NUMBER VARCHAR2(255) NOT NULL,
--	FK_CARD_LIST_ID NUMBER
--);
--
-- 카드 리스트 : 카드번호, 카드사, 회원정보
--CREATE SEQUENCE SEQ_CARD_LIST;
--CREATE TABLE TBL_CARD_LIST(
--	ID NUMBER CONSTRAINT PK_CARD_LIST PRIMARY KEY,
--	CARD_LIST_CARD_NUMBER NUMBER NOT NULL UNIQUE,
--	CARD_COMPANY_ID
--	CUSTOMER_ID
--);
--
-- 카드사 : 								+ 회원 정보(회원의 당사 카드 리스트)
--CREATE SEQUENCE SEQ_CARD_COMPANY;
--CREATE TABLE TBL_CARD_COMPANY(
--	ID NUMBER CONSTRAINT PK_CARD_COMPANY PRIMARY KEY,
--	CUSTOMER_ID NUMBER
--);
--
-- 상품 : 이름, 가격, 재고
--CREATE SEQUENCE SEQ_PRODUCT;
--CREATE TABLE TBL_PRODUCT(
--	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
--	PRODUCT_NAME VARCHAR2(255) NOT NULL,
--	PRODUCT_PRICE NUMBER NOT NULL,
--	PRODUCT_STOCK NUMBER DEFAULT 999
--);
--
-- 결제 테이블 : 기업, 사용자, 결제한 카드의 정보	+ 결제한 상품
--CREATE SEQUENCE SEQ_PAYMENT;
--CREATE TABLE TBL_PAYMENT(
--	ID NUMBER CONSTRAINT PK_PAYMENT PRIMARY KEY,
--	ENTERPRISE_ID
--	CUSTOMER_ID
--	CARD_NUMBER_ID
--	PRODUCT_ID
--);

-----

-- 회사 : 기업이름, 주소, 대표번호
-- 멤버 : 이름, 주소, 전화번호
-- 상품 : 회사FK
-- 카드 : 회원FK
-- 주문 : 회원FK, 상품FK
-- 결제 : 카드FK, 주문FK

-- 회사(COMPANY): 기업 이름, 주소, 대표번호
CREATE SEQUENCE SEQ_COMPANY;
CREATE TABLE TBL_COMPANY(
   ID NUMBER CONSTRAINT PK_COMPANY PRIMARY KEY,
   COMPANY_NAME VARCHAR2(255) NOT NULL,
   COMPANY_ADDRESS VARCHAR2(255),
   COMPANY_PHONE VARCHAR2(255)
);

-- 멤버(MEMBER): 이름, 주소, 전화번호
CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
   ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
   MEMBER_NAME VARCHAR2(255) NOT NULL,
   MEMBER_ADDRESS VARCHAR2(255) NOT NULL,
   MEMBER_PHONE VARCHAR2(255)
);

-- 상품(PRODUCT): 회사 FK
CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
   ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
   PRODUCT_NAME VARCHAR2(255),
   PRODUCT_PRICE NUMBER DEFAULT 0,
   PRODUCT_STOCK NUMBER DEFAULT 999,
   COMPANY_ID NUMBER,
   CONSTRAINT FK_PRODUCT_COMPANY FOREIGN KEY(COMPANY_ID)
   REFERENCES TBL_COMPANY(ID)
);

-- 카드(CARD): 회원 FK
CREATE SEQUENCE SEQ_CARD;
CREATE TABLE TBL_CARD(
   ID NUMBER CONSTRAINT PK_CARD PRIMARY KEY,
   CARD_NAME VARCHAR2(255),
   CARD_NUMBER VARCHAR2(255),
   CARD_DATE VARCHAR2(255),
   CARD_BANK VARCHAR2(255),
   MEMBER_ID NUMBER,
   CONSTRAINT FK_CARD_MEMBER FOREIGN KEY(MEMBER_ID)
   REFERENCES TBL_MEMBER(ID)
);

-- 주문(ORDER): 회원 FK, 상품 FK
CREATE SEQUENCE SEQ_ORDER;
CREATE TABLE TBL_ORDER(
   ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
   ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   MEMBER_ID NUMBER,
   PRODUCT_ID NUMBER,
   CONSTRAINT FK_ORDER_MEMBER FOREIGN KEY(MEMBER_ID)
   REFERENCES TBL_MEMBER(ID),
   CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY(PRODUCT_ID)
   REFERENCES TBL_PRODUCT(ID)
);

-- 결제(PAY): 카드 FK, 주문 FK
CREATE SEQUENCE SEQ_PAY;
CREATE TABLE TBL_PAY(
   ID NUMBER CONSTRAINT PK_PAY PRIMARY KEY,
   PAY_STATUS CHAR(20) DEFAULT '결제 대기',
   PAY_COMPLETE_DATE DATE,
   CARD_ID NUMBER,
   ORDER_ID NUMBER,
   CONSTRAINT FK_PAY_CARD FOREIGN KEY(CARD_ID)
   REFERENCES TBL_CARD(ID),
   CONSTRAINT FK_PAY_ORDER FOREIGN KEY(ORDER_ID)
   REFERENCES TBL_ORDER(ID)
);

