-- 게시판 최신글 정렬
SELECT tp.ID, tp.POST_TITLE, tu.USER_EMAIL
FROM TBL_POST tp
JOIN TBL_USER tu
ON tp.USER_ID = tu.ID
ORDER BY ID DESC;

--댓글을 단 사용자
SELECT tr.ID, tr.REPLY_CONTENT, tu.USER_EMAIL
FROM TBL_REPLY tr
JOIN TBL_USER tu
ON tr.USER_ID = tu.ID;

/*
 * SQL의 실행 순서
 * 
 * FROM > JOIN > ON > WHERE > GROUP BY > HAVING > SELECT > ORDER BY
 * 
 * */

-- 주문자 정보 조회
-- 주문 날짜, 사용자의 이름
SELECT tbo.ORDER_START_DATE, tbb.BUYER_NAME
FROM TBL_ORDER tbo
JOIN TBL_BUYER tbb
ON tbo.BUYER_ID = tbb.ID;

-- 가장 인기 많은 상품을 구매한 사용자의 정보와 상품 명을 조회

SELECT tp.PRODUCT_NAME, tb.*
FROM (
	SELECT BUYER_ID, PRODUCT_ID
	FROM TBL_ORDER
	WHERE PRODUCT_ID = (
		SELECT PRODUCT_ID
		FROM TBL_ORDER
		GROUP BY PRODUCT_ID
		HAVING COUNT(PRODUCT_ID) = (
			SELECT MAX(COUNT(PRODUCT_ID))
			FROM TBL_ORDER
			GROUP BY PRODUCT_ID
		)
	)
) MADETABLE
JOIN TBL_PRODUCT tp
ON MADETABLE.PRODUCT_ID = tp.ID
JOIN TBL_BUYER tb
ON MADETABLE.BUYER_ID = tb.ID;

-- 1) 상품 이름과 총 판매 매출 조회
SELECT PRODUCT_NAME, SELLING * PRODUCT_PRICE AS "매출"
FROM (
	SELECT COUNT(PRODUCT_ID) AS "SELLING", PRODUCT_ID
	FROM TBL_ORDER
	GROUP BY PRODUCT_ID
) tbo
JOIN TBL_PRODUCT tbb
ON tbo.PRODUCT_ID = tbb.ID;

-- 2) 상품을 구매한 20 ~ 30대 구매자의 수 조회
SELECT COUNT(ID)
FROM(
	SELECT BUYER_ID
	FROM TBL_ORDER
	GROUP BY BUYER_ID
) tbo
JOIN TBL_BUYER tbb
ON tbo.BUYER_ID = tbb.ID
WHERE tbb.BUYER_AGE >= 20 AND tbb.BUYER_AGE < 30;

--
--SELECT COUNT(ID) || '건' AS "20~30대 주문 개수"
--FROM TBL_ORDER
--WHERE BUYER_ID IN (
--   SELECT ID
--   FROM TBL_BUYER
--   WHERE BUYER_AGE >= 20 AND BUYER_AGE <= 39
--);
--

-- 3) 뉴발란스를 구매한 20대 구매자의 이름 조회
SELECT tbb.BUYER_NAME
FROM (
	SELECT BUYER_ID
	FROM TBL_ORDER
	WHERE PRODUCT_ID IN (
		SELECT ID
		FROM TBL_PRODUCT
		WHERE PRODUCT_BRAND LIKE '뉴발란스'
	)
) tbo
JOIN TBL_BUYER tbb
ON tbo.BUYER_ID = tbb.ID
WHERE tbb.BUYER_AGE >=20 AND tbb.BUYER_AGE < 30;

--4) 여성의 나이대별 평균 지출 금액 조회
SELECT TBB.BUYER_AGE AS "나이", ROUND(AVG(TBP.PRODUCT_PRICE)) AS "지출 금액"
FROM TBL_ORDER TBO
JOIN TBL_BUYER TBB 
ON TBO.BUYER_ID = TBB.ID 
JOIN TBL_PRODUCT TBP 
ON TBO.PRODUCT_ID = TBP.ID 
WHERE TBB.BUYER_GENDER = '여'
GROUP BY TBB.BUYER_AGE;

--5) 쇼핑몰의 총 판매 액수 조회
SELECT SUM(tbp.PRODUCT_PRICE) AS "쇼핑몰의 총 판매 액수"
FROM TBL_ORDER tbo
JOIN TBL_PRODUCT tbp 
ON tbo.PRODUCT_ID = tbp.ID;

--6) 가장 매출이 적은 상품을 구매한 사용자의 이름과, 상품명 조회
SELECT tbb.BUYER_NAME, tbp.PRODUCT_NAME 
FROM(
	SELECT BUYER_ID , PRODUCT_ID 
	FROM TBL_ORDER
	WHERE PRODUCT_ID = (
		SELECT PRODUCT_ID
			FROM(
				SELECT PRODUCT_ID, SUM(PRODUCT_PRICE) AS "해당 아이디의 매출" 
				FROM TBL_ORDER tbo
				JOIN TBL_PRODUCT tbp 
				ON tbo.PRODUCT_ID = tbp.ID
				GROUP BY PRODUCT_ID
				ORDER BY "해당 아이디의 매출"
			)
		WHERE ROWNUM <= 1
	)
) tbo
JOIN TBL_BUYER tbb
ON	tbo.BUYER_ID = tbb.ID
JOIN TBL_PRODUCT tbp
ON	tbo.PRODUCT_ID = tbp.ID;

--7) 경기도에 거주한 사람이 구매한 상품과, 사용자 정보를 조회
SELECT tbp.*, tbb.*
FROM(
	SELECT BUYER_ID, PRODUCT_ID
	FROM TBL_ORDER
	WHERE BUYER_ID = (
		SELECT ID
		FROM TBL_BUYER
		WHERE BUYER_ADDRESS LIKE '%경기도%'
	)
) tbo
JOIN TBL_BUYER tbb
ON tbo.BUYER_ID = tbb.ID
JOIN TBL_PRODUCT tbp
ON tbo.PRODUCT_ID = tbp.ID;

--8) 30대 남성이 가장 많이 구매한 상품의 이름 조회
SELECT PRODUCT_NAME
FROM TBL_PRODUCT
WHERE ID = (
	SELECT PRODUCT_ID
	FROM(
		SELECT PRODUCT_ID
		FROM TBL_ORDER
		WHERE BUYER_ID IN (
			SELECT ID
			FROM TBL_BUYER
			WHERE BUYER_GENDER = '남' AND BUYER_AGE BETWEEN 30 AND 39
		)
		GROUP BY PRODUCT_ID
		ORDER BY COUNT(PRODUCT_ID) DESC
	)
	WHERE ROWNUM <= 1
);

--9) 가장 적게 판매된 상품의 이름
SELECT PRODUCT_NAME 
FROM TBL_PRODUCT
WHERE ID IN (
	SELECT PRODUCT_ID
	FROM(
		SELECT PRODUCT_ID, COUNT(PRODUCT_ID) 
		FROM TBL_ORDER
		GROUP BY PRODUCT_ID
		ORDER BY COUNT(PRODUCT_ID)
	)
	WHERE ROWNUM <= 2
);

--10) 평균 나이보다 많은 사용자들이 구매한 상품과 사용자의 정보 조회
SELECT tbp.*, tbm.*
FROM TBL_ORDER tbo
JOIN(
	SELECT *
	FROM TBL_BUYER
	WHERE BUYER_AGE > (
		SELECT AVG(BUYER_AGE) 
		FROM TBL_BUYER
	)
) tbm
ON tbo.BUYER_ID  = tbm.ID
JOIN TBL_PRODUCT tbp
ON tbo.PRODUCT_ID  = tbp.ID;

--11) 20대 여성이 구매한 상품 이름과 주문 건수 조회
SELECT tbp.PRODUCT_NAME, COUNT(PRODUCT_NAME)
FROM(
	SELECT *
	FROM TBL_ORDER
	WHERE PRODUCT_ID IN (
		SELECT PRODUCT_ID
		FROM TBL_ORDER
		WHERE BUYER_ID IN (
			SELECT ID 
			FROM TBL_BUYER
			WHERE BUYER_GENDER = '여' AND BUYER_AGE >= 20 AND BUYER_AGE < 30
		)
	)
) tbm
JOIN TBL_PRODUCT tbp
ON tbm.PRODUCT_ID = tbp.ID
GROUP BY PRODUCT_NAME; 

--12) 가장 인기가 없는 상품 조회
SELECT *
FROM TBL_PRODUCT
WHERE ID IN (
	SELECT PRODUCT_ID
	FROM(
		SELECT PRODUCT_ID, COUNT(PRODUCT_ID) 
		FROM TBL_ORDER
		GROUP BY PRODUCT_ID
		ORDER BY COUNT(PRODUCT_ID)
	)
	WHERE ROWNUM <= 2
);
