/*
	사용자는 장바구니에 커피를 담을 수 있다.
	사용자 정보는 이름, 주소, 전화번호가 필요하다.
	커피의 정보도 필요합니다. 커피의 정보는 이름, 가격, 재고입니다.
	장바구니에 담을 시 사용자의 정보와 커피가 필요합니다.
*/

CREATE SEQUENCE SEQ_USER;
CREATE TABLE TBL_USER(
	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_NAME VARCHAR2(255) NOT NULL,
	USER_ADDRESS VARCHAR2(255) NOT NULL,
	USER_PHONE VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE SEQ_COFFEE;
CREATE TABLE TBL_COFFEE(
	ID NUMBER CONSTRAINT PK_COFFEE PRIMARY KEY,
	COFFEE_NAME VARCHAR2(255) NOT NULL,
	COFFEE_PRICE NUMBER NOT NULL,
	COFFEE_STOCK NUMBER DEFAULT 999
);

CREATE SEQUENCE SEQ_CART;
CREATE TABLE TBL_CART(
	ID NUMBER CONSTRAINT PK_CART PRIMARY KEY,
	FK_USER NUMBER,
	FK_COFFEE NUMBER,
	CONSTRAINTS FK_CART_USER FOREIGN KEY(FK_USER)
	REFERENCES TBL_USER(ID),
	CONSTRAINT
	
);
