CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) NOT NULL,
	PRODUCT_PRICE NUMBER,
	PRODUCT_STOCK NUMBER DEFAULT 0
);

CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(255) NOT NULL UNIQUE,
	MEMBER_PASSWORD VARCHAR2(255) NOT NULL,
	MEMBER_NAME VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE SEQ_ORDER;
CREATE TABLE TBL_ORDER(
	ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	PRODUCT_ID NUMBER NOT NULL,
	PRODUCT_COUNT NUMBER DEFAULT 1,
	CONSTRAINT FK_ORDER_MEMBER FOREIGN KEY (MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY(PRODUCT_ID)
	REFERENCES TBL_PRODUCT(ID)
);


SELECT * FROM TBL_PRODUCT;
SELECT * FROM TBL_MEMBER;
SELECT * FROM TBL_ORDER;

SELECT 
	tbo.ID, tbo.MEMBER_ID, tbo.PRODUCT_ID,
	tbo.PRODUCT_COUNT, tbo.PRODUCT_COUNT * tbp.PRODUCT_PRICE AS "ORDER_TOTAL_PRICE",
	tbp.PRODUCT_NAME, tbp.PRODUCT_PRICE,
	tbp.PRODUCT_STOCK, tbm.MEMBER_EMAIL,
	tbm.MEMBER_NAME
FROM TBL_ORDER tbo
JOIN TBL_PRODUCT tbp 
ON tbo.PRODUCT_ID = tbp.ID
JOIN TBL_MEMBER tbm
ON tbo.MEMBER_ID = tbm.ID
ORDER BY tbo.ID DESC;

--INSERT INTO TBL_ORDER
--VALUES(SEQ_MEMBER.NEXTVAL, #{memberId}, #{productId}, #{productCount});

SELECT MEMBER_EMAIL
FROM  TBL_MEMBER
WHERE MEMBER_EMAIL = 'test123@test.com' AND MEMBER_PASSWORD = 'test123!@#';

--SELECT ID
--FROM TBL_ORDER
--WHERE MEMBER_EMAIL = #{memberEmail}

UPDATE TBL_PRODUCT
SET PRODUCT_NAME, = #{productName}, PRODUCT_PRICE = #{productPrice}, PRODUCT_STOCK = #{productStock}
WHERE ID = #{id}

