CREATE SEQUENCE SEQ_NCS_PRODUCT;
CREATE TABLE TBL_NCS_PRODUCT(
	ID NUMBER CONSTRAINT PK_NCS_PRODUCT PRIMARY KEY,
	NCS_PRODUCT_NAME VARCHAR2(255),
	NCS_PRODUCT_PRICE NUMBER,
	NCS_PRODUCT_SELLER VARCHAR2(255)
);

SELECT * FROM TBL_NCS_PRODUCT;

--INSERT INTO TBL_NCS_PRODUCT
--VALUES (SEQ_NCS_PRODUCT.NEXTVAL, '상품명', 1230, '판매자');
--
--INSERT INTO TBL_NCS_PRODUCT
--VALUES (SEQ_NCS_PRODUCT.NEXTVAL, ${ncsProductName}, ${ncsProductPrice}, ${ncsProductSeller})

SELECT ID, NCS_PRODUCT_NAME, NCS_PRODUCT_PRICE, NCS_PRODUCT_SELLER
FROM TBL_NCS_PRODUCT

