CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) NOT NULL,
	PRODUCT_PRICE NUMBER,
	PRODUCT_STOCK NUMBER DEFAULT 0
);

SELECT * FROM TBL_PRODUCT;

SELECT ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_STOCK
FROM TBL_PRODUCT
WHERE ID = 3;



-----

CREATE SEQUENCE SEQ_POST;
CREATE TABLE TBL_POST(
	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
	POST_TITLE VARCHAR2(255) NOT NULL,
	POST_CONTENT VARCHAR2(255) NOT NULL
);

SELECT * FROM TBL_POST;

--1. 게시글 작성

INSERT INTO TBL_POST 
VALUES (SEQ_POST.NEXTVAL, 'asdf', 'a');

--2. 게시글 목록

SELECT ID, POST_TITLE, POST_CONTENT
FROM TBL_POST;

--3. 게시글 상세보기
      SELECT ID, POST_TITLE, POST_CONTENT
			FROM TBL_POST
			WHERE ID = 3

--4. 게시글 수정

UPDATE TBL_POST
SET POST_TITLE = #{POST_TITLE}, POST_CONTENT = #{POST_CONTENT}
FROM ID = #{ID};

--5. 게시글 삭제
DELETE
FROM TBL_POST
WHERE ID = #{ID};
