--CREATE TABLE TBL_USER(
--	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
--	USER_NAME VARCHAR2(255),
--	USER_AGE NUMBER,
--	USER_ADDRESS VARCHAR2(255)
--);

-- 상품 PRODUCT
-- 상품 이름, 상품 가격, 상품 재고, 상품 설명
CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
--	ㄴ> 개체 무결성
	PRODUCT_NAME VARCHAR2(255) UNIQUE NOT NULL,
--	ㄴ> 도메인 무결성
	PRODUCT_PRICE NUMBER NOT NULL,
	PRODUCT_STOCK NUMBER DEFAULT 999,
	PRODUCT_DESCRIPTION VARCHAR2(255)
);

DROP TABLE TBL_PRODUCT;
-- 테이블 TBL_PRODUCT 삭제

--SQL언어의 값은 '' (싱글쿼터) 사용

--데이터 추가(DML)
INSERT INTO TBL_PRODUCT(ID, PRODUCT_NAME, PRODUCT_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, '이승찬의 맥북', 1500000);

INSERT INTO TBL_PRODUCT(ID, PRODUCT_NAME, PRODUCT_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, '배승원의 그램', 15000);

--INSERT INTO TBL_PRODUCT(ID, PRODUCT_NAME, PRODUCT_PRICE)
--VALUES(1, '배승원의 그램', 15000);
-- ㄴ> 도메인 무결성 위반 > 허용된 범위 외의 값을 넣었으므로

--데이터 조회(DML)
SELECT * FROM TBL_PRODUCT;

--컬럼 추가
ALTER TABLE TBL_PRODUCT ADD REVIEW_COUNT NUMBER;

--컬럼 수정
ALTER TABLE TBL_PRODUCT MODIFY REVIEW_COUNT NUMBER DEFAULT 0;

--컬럼 삭제
ALTER TABLE TBL_PRODUCT DROP COLUMN REVIEW_COUNT;

---
---

--MEMBER 테이블
--이름, 나이, 성별, 주소
CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_NAME VARCHAR2(255) UNIQUE NOT NULL,
	MEMBER_AGE NUMBER NOT NULL,
	MEMBER_GENDER VARCHAR2(255),
	MEMBER_ADDRESS VARCHAR2(255)
);
--사용자를 두명 추가
INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, MEMBER_ADDRESS)
VALUES(SEQ_MEMBER.NEXTVAL, '이름1', 20, '남성', '경기도');
INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, MEMBER_ADDRESS)
VALUES(SEQ_MEMBER.NEXTVAL, '이름2', 21, '여성', '서울');
--컬럼 추가 ->> 등급(CHAR타입)
ALTER TABLE TBL_MEMBER ADD MEMBER_RATING CHAR(255);
--등급 컬럼을 VARCHAR2 타입으로 변경
ALTER TABLE TBL_MEMBER MODIFY MEMBER_RATING VARCHAR2(255);
--등급 컬럼 삭제
ALTER TABLE TBL_MEMBER DROP COLUMN MEMBER_RATING;

DROP TABLE TBL_MEMBER;
DROP SEQUENCE SEQ_MEMBER;
SELECT * FROM TBL_MEMBER;
